# Generated by Django 5.0.4 on 2024-06-08 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='idkomentarisan',
            field=models.ForeignKey(db_column='IdKomentarisan', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentar_idkomentarisan_set', to='proj.korisnik'),
        ),
    ]
